language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - date
  - curl -L https://github.com/krlmlr/texlive-squashfs/raw/master/out/texlive.tar.xz | tar -JxC ~
  - date

# command to install dependencies
install:
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script: make VOL=1 PAGES=5 USER_NAME="BLANK" USER_EMAIL="BLANK"